### ISSUE TITLE
Exception in function shouldRetryRequest() when checking HTTP methods to retry

### ISSUE THREAD

**Issue by alex-polunochev** [JustinBeckwith/retry-axios#1]
In function `shouldRetryRequest` there's this block of code
```
    // Only retry with configured HttpMethods.
    if (!err.config.method ||
        config.httpMethodsToRetry.indexOf(err.config.method.toUpperCase()) < 0) {
        return false;
    }
```
that fails evaluating second condition, because `httpMethodsToRetry` is an object, not an array.

Below goes the output from dev console, when the breakpoint was set on the line given above ^^^:
```
config.httpMethodsToRetry
{0: "GET", 1: "HEAD", 2: "OPTIONS", 3: "DELETE", 4: "PUT"}
```

That looks different from what gets set in `raxConfig`
```
    const raxConfig = {
    ....
        
      // HTTP methods to automatically retry.  Defaults to:
      // ['GET', 'HEAD', 'OPTIONS', 'DELETE', 'PUT']
      httpMethodsToRetry: ['GET', 'HEAD', 'OPTIONS', 'DELETE', 'PUT'],
    }
```

**Comment by JustinBeckwith** [comment]
Weird.  `httpMethodsToRetry` should be an array, not an object.  It would be super helpful if you could share your code :)

**Comment by RobertFischer** [comment]
I am getting this, too. 

Here's my relevant code.

```
import Axios from 'axios';
import { attach as raxAttach, getConfig as raxConfig } from 'retry-axios';

const createAxios = () => {
  const http = Axios.create();
  http.defaults.timeout = 60*1000;
  http.defaults.validateStatus = (status) => (status >= 200 && status < 300) || (status == 404);
  http.defaults.raxConfig = {
    instance: http,
    retry: 5,
    noResponseRetries: 100,
    retryDelay: 250,
    httpStatusCodesToRetry: [[100, 199], [420, 429], [500, 599]],
    onRetryAttempt: (err) => {
      try {
        console.info("Retrying request", err, raxConfig(err))
      } catch(e) {
        throw new Error("Error logging the retry of a request: " + e);
      }
    },
  };
  raxAttach(http);
  return http;
};
```

**Comment by chaitya1001** [comment]
I am also getting error,

Here is my relevant code,
```
axios.defaults.raxConfig= {
  // Retry 3 times on requests that return a response (500, etc) before giving up.  Defaults to 3.
  retry: 3,

  // Retry twice on errors that don't return a response (ENOTFOUND, ETIMEDOUT, etc).
  noResponseRetries: 3,

  // Milliseconds to delay at first.  Defaults to 100.
  retryDelay: 0,

  // HTTP methods to automatically retry.  Defaults to:
  // ['GET', 'HEAD', 'OPTIONS', 'DELETE', 'PUT']
  httpMethodsToRetry: ['GET', 'DELETE', 'PUT', 'POST'],

  // The response status codes to retry.  Supports a double
  // array with a list of ranges.  Defaults to:
  // [[100, 199], [429, 429], [500, 599]]
  httpStatusCodesToRetry: [[100, 199], [429, 429], [500, 599]],

  // If you are using a non static instance of Axios you need
  // to pass that instance here (const ax = axios.create())
  instance: axios,

  // You can detect when a retry is happening, and figure out how many
  // retry attempts have been made
  onRetryAttempt: (err) => {
    const cfg = rax.getConfig(err);
    console.log(`Retry attempt #${cfg.currentRetryAttempt}`);
  }
};
const id = rax.attach(axios);
```

And here is the error,

```
TypeError: config.httpMethodsToRetry.indexOf is not a function
    at shouldRetryRequest (/Users/chaityashah/FracTEL/skrum/node_modules/retry-axios/build/src/index.js:96:35)
    at onError (/Users/chaityashah/FracTEL/skrum/node_modules/retry-axios/build/src/index.js:58:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by luke3butler** [comment]
I debugged this issue and found the root of the problem in the Axios package.

The issue only happens on retry, and the reason is because of a configuration merge function that doesn't have deep-copy capability.

Offending line here: https://github.com/axios/axios/blob/ad1195f0702381a77b4f2863aad6ddb1002ffd51/lib/core/Axios.js#L35

It appears that this merge function has entirely changed (with deep-copy fixes) for v0.18.x releases, which are yet to be released.

**Comment by jordanfloyd** [comment]
also had this issue. An effective workaround for the moment is to pass a custom shouldRetry function and check the type of `config.httpMethodsToRetry` and get the values into something useful before checking. Not ideal, but relatively easy to fix until a new version of axios is released which resolves the issue.

**Comment by mpyw** [comment]
https://github.com/axios/axios/blob/4f98acc57860721c639f94f5772138b2af273301/lib/core/Axios.js#L37

https://github.com/axios/axios/blob/4f98acc57860721c639f94f5772138b2af273301/lib/core/mergeConfig.js#L13-L51

**Comment by gpetrioli** [comment]
@opyate The same problem exists with the `httpMethodsToRetry` config property. 
Could you please patch that as well, since it is the same problem ?

**Comment by georgyfarniev** [comment]
Having this problem as well

**Comment by mpyw** [comment]
@georgyfarniev I abondoned `retry-axios` and wrap `axios` by myself. Currently this library is completely broken.

**Comment by mpyw** [comment]
I also propose that peer dependency be correctly defined.

```js
  "peerDependencies": {
    "axios": "*" // <- ??
  },
```

**Comment by JustinBeckwith** [comment]
Greetings! When you say the latest version - what specific version are you using?

**Comment by mpyw** [comment]
@JustinBeckwith 

`v0.19.0-beta.1`. Please see [my comment](https://github.com/JustinBeckwith/retry-axios/issues/1#issuecomment-461276410).
Now options are completely whitelisted and it doesn't accept `raxConfig`.

**Comment by opyate** [comment]
@mpyw shall we create separate issues for the peer dependency and whitelisting stuff?

**Comment by avindra** [comment]
Do you guys know of a drop in (or as close to drop in as possible) replacement for axios?

This library is on the critical path for a lot of our apps, and problems like these cause serious issues and slow down development.

**Comment by JustinBeckwith** [comment]
I wrote https://github.com/googleapis/gaxios/ to be that drop in replacement based on node-fetch 🙃 It's part of the reason I don't spend a ton of time in this particular module. It has retries baked in.
