### ISSUE TITLE
I am not being able to replace the default config values

### ISSUE THREAD

**Issue by harrydema** [JustinBeckwith/retry-axios#101]
Although I set the retry number to 2, the raxConfig shows that the retry keeps at 3.

![image](https://user-images.githubusercontent.com/13423169/78372745-0bb74a00-75a0-11ea-94ec-35e3d9110b0f.png)

**Comment by sk-** [comment]
Probably a duplicate of #90

**Comment by JustinBeckwith** [comment]
Hey folks - I believe the latest release of axios fixed this issue 🎉  Let me know if you're still running into issues!
