### ISSUE TITLE
Package version 0.0.0 out of sync with NPM

### ISSUE THREAD

**Issue by AndyOGo** [JustinBeckwith/retry-axios#108]
https://github.com/JustinBeckwith/retry-axios/blob/fc8117e838c4e6764969e844707354bb8f85816d/package.json#L3

https://www.npmjs.com/package/retry-axios/v/latest

**Comment by JustinBeckwith** [comment]
Greetings!  The package version is set automatically as the package is released :)  Let me know if you're running into any problems!

**Comment by AndyOGo** [comment]
Hey man,
Thank you for your quick feedback.

Yeah the `version` field is correct on NPM.
Though it's not committed within the repo's `package.json`.
Guess, it's like that on purpose?

**Comment by JustinBeckwith** [comment]
Yes, that is on purpose :) There is a robot that is responsible for orchestrating my releases via semantic-release.  It sets the version as part of the release process, so the version in package.json never actually gets updated.  I set it to 0 to signal to folks "you probably don't wanna touch that" 😆

**Comment by AndyOGo** [comment]
I see, semantic-release is awesome
