### ISSUE TITLE
is project still maintained?

### ISSUE THREAD

**Issue by sk-** [JustinBeckwith/retry-axios#125]
Hi @JustinBeckwith I wanted to check if this project is still maintained and whether you would be willing to accept contributions.

I see that there are a couple of duplicated issues, dating a long back, and also there are some new issues reported.

**Comment by JustinBeckwith** [comment]
👋 I mean sorta, not really, kinda.  I don't personally use this library anymore, as I ended up writing an [HTTP client that suited our needs](https://github.com/googleapis/gaxios).   If folks make a PR, and it seems reasonable, I'm happy to work with you to land it and ship.

**Comment by sk-** [comment]
Thanks for the honest response. Maybe it'd be good to put a notice at the top of the README and add some collaborators.

**Comment by JustinBeckwith** [comment]
Sure thing - always happy to accept contributions :) For now I still manage to keep things relatively up to date, so I'm gonna close this out.  If there are specific issues folks want to help out with, I will happily review PRs!

**Comment by sk-** [comment]
In case anyone is interested, we ended up building our own interceptor to handle retries.
