### ISSUE TITLE
Add "PATCH" operations to the httpMethodsToRetry

### ISSUE THREAD

**Issue by iag** [JustinBeckwith/retry-axios#157]
Just a small enhancement, it may be useful to also support HTTP PATCH operations by default in the httpMethodsToRetry Array.

**Comment by JustinBeckwith** [comment]
Greetings, and thanks for the suggestion!  The current list of methods in `httpMethodsToRetry` are all ones which _should_ be idempotent.  The `PATCH` HTTP method typically is not considered to be idempotent.

From https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH:

> A PATCH is not necessarily idempotent, although it can be. Contrast this with PUT; which is always idempotent. The word "idempotent" means that any number of repeated, identical requests will leave the resource in the same state. For example if an auto-incrementing counter field is an integral part of the resource, then a PUT will naturally overwrite it (since it overwrites everything), but not necessarily so for PATCH.

> PATCH (like POST) may have side-effects on other resources.

The good news is that for your use cases, if you're sure that submitting the `PATCH` won't have side effects, you can override the default methods.

**Comment by iag** [comment]
That makes a lot of sense; thanks for considering!
