### ISSUE TITLE
Question re: max retry delay

### ISSUE THREAD

**Issue by padamstx** [JustinBeckwith/retry-axios#164]
Hi,
I work in the IBM Cloud Developer Experience group and we're considering the use of this package in our Node SDK "core" library (an enabling layer that is a dependency of our various IBM Cloud Node SDKs).

In studying the package a bit, it looks like there is perhaps one small requirement that we have that might not currently be supported.  We would want to use the exponential backoff policy, but also be able to cap the delay time by some user-configurable maximum delay time.  It's possible I missed something, but it doesn't appear that the package currently supports this.

Assuming that's true, would you be open to accepting a PR which introduces a new optional `RetryConfig` field perhaps named something like `maxRetryDelay` that would be used such that, if specified, it serves as the max delay computed by this section of `onBackoffPromise`:
```
      if (config.backoffType === 'linear') {
        delay = config.currentRetryAttempt! * 1000;
      } else if (config.backoffType === 'static') {
        delay = config.retryDelay!;
      } else {
        delay = ((Math.pow(2, config.currentRetryAttempt!) - 1) / 2) * 1000;
      }
``` 

Thanks!

**Comment by JustinBeckwith** [comment]
That sounds great!  Happy to accept a PR.

**Comment by padamstx** [comment]
@JustinBeckwith Thanks Justin, we'll get a PR submitted for this.   I'm thinking that this new maxRetryDelay value would only apply to the exponential backoff case (it wouldn't affect the linear or static scenarios).  Do you agree?

**Comment by JustinBeckwith** [comment]
Looks like this was applied and shipped already here :)  https://github.com/JustinBeckwith/retry-axios/pull/165
