### ISSUE TITLE
Problem with 3.0.0

### ISSUE THREAD

**Issue by jakepearson** [JustinBeckwith/retry-axios#189]
Hi,
Dependabot updated my service deps this morning and our e2e tests started to fail. We now get this error in our code that is generated off off an openapi spec. Any ideas on how to work around it? Error message is below.

```
    Cannot find module 'retry-axios' from '<path-to-my-code>'

    Require stack:
      src/openapi/2021-06-05/client/base.ts
      src/openapi/2021-06-05/client/api/default-api.ts
      src/openapi/2021-06-05/client/api.ts
      src/openapi/2021-06-05/client/index.ts
      src/e2e/helper.ts
      src/e2e/translate/base-edi-validation.e2e.ts

      21 | // Some imports not used depending on template conditions
      22 | // @ts-ignore
    > 23 | import * as rax from 'retry-axios';
         |                      ^

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (<path-to-my-code>:23:22)
```

**Comment by JustinBeckwith** [comment]
Weird. I can't think of anything that would specifically cause this ... but usually when I see `// @ts-ignore` it means I'm about to have a bad time :) This will sound silly, but have you tried deleting your `package-lock.json`, running `npm install`, and trying again?

**Comment by JustinBeckwith** [comment]
It would be _super_ helpful if you had a small repro I could work from - if you have anything else to share, or any more details ... let me know!

**Comment by zibok** [comment]
Or @jakepearson did you find a way to make it work?
