### ISSUE TITLE
onRetryAttempt how to change baseUrl dinamically while retrying

### ISSUE THREAD

**Issue by leopucci** [JustinBeckwith/retry-axios#196]
Hey there!
Any hints on how I could change the baseurl on the retry attempt?

```
onRetryAttempt: (err) => {
    const cfg = rax.getConfig(err);
    childLogger.error(`myRaxConfig Retry attempt #${cfg.currentRetryAttempt}`);
  }
```

**Comment by JustinBeckwith** [comment]
What does your retry pattern look like?  If you're changing the underlying base url, I am guessing you don't need things like backoff ... heck I would wager you don't even need this library :) Instead you could just wrap things in a try/catch, and if it throws, just retry immediately with the new base url. 

That having been said .... you should be able to do something like:

```js
onRetryAttempt: (err) => {
    const cfg = rax.getConfig(err);
    cfg.baseUrl = 'http://whatevs';
  }
```
