### ISSUE TITLE
Also supports CommonJS 

### ISSUE THREAD

**Issue by yutak23** [JustinBeckwith/retry-axios#218]
I believe this package is currently a [pure ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) package, but the [data](https://github.com/wooorm/npm-esm-vs-cjs/tree/main#data) shows that there are still many CommonJS libraries and CommonJS is still being used.

Therefore, it would be very helpful if this package could also support CommonJS.

**Comment by JustinBeckwith** [comment]
Thanks for the issue!  From the PR:

> Greetings! While I appreciate the PR - I'm not really interested in adding dual CJS support. ES Modules have been out for quite some time, and many, many modules have moved towards ESM only. I'm not really looking for the additional testing and maintenance burden of dual support.

**Comment by qodeboy** [comment]
Axios itself is cjs compliant, so the library accompanying axios should.
