### ISSUE TITLE
statusCodesToRetry doesn't work when Http Status Code is 2xx

### ISSUE THREAD

**Issue by shiyouping** [JustinBeckwith/retry-axios#25]
When specify statusCodesToRetry as 2xx, this doesn't work because of the following code:

```` Javascript
export function attach(instance?: AxiosInstance) {
  instance = instance || axios;
  return instance.interceptors.response.use(onFulfilled, onError);
}
````

onError will be only triggered when the Http Status Code is not 2xx. That means all retries this library will perform only works when Http Status Code is not 2xx.

**Comment by KayHS** [comment]
@shiyouping did you figure out how to retry when status was 2xx?

**Comment by shiyouping** [comment]
> @shiyouping did you figure out how to retry when status was 2xx?

Yes, but I didnt use this library. I implemented the retry by myself. You can refer to this file https://github.com/shiyouping/rtalpha/blob/master/web/src/kernel/network/request-sender.js

**Comment by JustinBeckwith** [comment]
Greetings folks!  I'm a tad confused :) If the API returns a 2xx response, that typically means "it worked".  Can y'all give me an example of a 2xx response that you would retry?

**Comment by KayHS** [comment]
@JustinBeckwith hey yes there is a usecase i am using an API which is processing some data. I short poll this data to retry until the data is ready. 

When the data is not ready i receive a 200 response with an empty []
When the data is ready i receive a 200 response with a non-empty [].

**Comment by shubhamd** [comment]
@JustinBeckwith, In my case, I am receiving invalid JSON with status code 200, it is an API I don't have control over, so If there is a way to retry based on responseBody, that would be great!

**Comment by shubhamd** [comment]
One of the ways we can implement this by *not* actually implementing this is - 
In `axios-retry`, we start catching the errors thrown by custom interceptors (request/response) of `axios`. In this way people can write their own custom interceptors and validate the data the way they want. @JustinBeckwith, Thoughts?

**Comment by JustinBeckwith** [comment]
So to be honest - this is far enough outside the goal of the library, that I don't want to add support for managing retries on 2xx responses.  The interceptor API in axios is good enough that you should be able to plug in there, and lift whatever bits of backoff stuff you need from here.  Apologies!
