### ISSUE TITLE
Error when a method called inside the axios interceptor throws a custom error

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [JustinBeckwith/retry-axios#32]
Error `cannot read property 'raxConfig' of undefined` is occurring when a method called inside the axios interceptor throws a custom error.

**Example:**
**Interceptor:**
```
axios.interceptors.request.use (
	async request => {
		request.headers.Authorization = await auth.getToken();
		return request
	},
	error => { ... }
);
```
**Method (`auth.getToken()`):**
```
	async getToken() {
		if (!this.auth.getCachedSession().isValid()) {
			throw new Error('Session has expired.');
		} else {
			return this.getAccessToken();
		}
	}
```
This error is happenning because custom error does not have a `config` object. Then the `onError` method of the `retry-axios` try to access `error.config,raxConfig` 

**A possible fix would be modifying `onError` function as following.**
```
function onError(err) {
	if (!err.config) {
		return Promise.reject(err);
	}
        ...
}
```

**Comment by JustinBeckwith** [comment]
Greetings!  I *think* this could have been fixed in a recent release.  Could I trouble you to give this another shot?
