### ISSUE TITLE
Transpile to ES5

### ISSUE THREAD

**Issue by f1cognite** [JustinBeckwith/retry-axios#37]
I want to use this package but it contains non-es5 keywords (`const`) in the output file.

**Comment by JustinBeckwith** [comment]
Greetings!  What type of environment are you trying to support?  `const` is supported by any reasonably modern version of node or the browser:
- https://caniuse.com/#search=const
- https://node.green/#ES2015-bindings-const-basic-support

**Comment by valerii-cognite** [comment]
Hi @JustinBeckwith Please correct me if I'm wrong, but I believe an explanation can be found here https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify. So all the applications which are build on top older create-react-app version on any similar environment will fail to build without library being transpiled into es5

**Comment by f1cognite** [comment]
@JustinBeckwith Anything that is blocking the merge of this PR #38 ?

**Comment by JustinBeckwith** [comment]
I'm a little concerned about down-leveling compilation that far, as it does come at a perf cost - especially as we're getting closer to things like broad support for native async/await and such.  

Reading that link you shared - it feels like the answer is to upgrade to a recent version of `react-scripts`, no?  Just want to make sure we're making a change like this for the right reasons :)

**Comment by f1cognite** [comment]
Yes, I see your point @JustinBeckwith. Another solution is to create two different builds (es6 and es5).

We ended up downgrading to `retry-axios@0.3.2` which was in ES5.
So I think we can close the issue and PR?
