### ISSUE TITLE
Cannot read property 'raxConfig' undefined

### ISSUE THREAD

**Issue by vitaly87** [JustinBeckwith/retry-axios#59]
`  const rax = require('retry-axios');
  const 
      axios
   = require('axios');`

```
    const response = await axios({
                method: 'post',
                url: url,
                headers: {
                    'Accept': 'application/json;charset=utf-8',
                    'Content-Type': 'application/json;charset=utf-8'
                },
                responseType: 'json',
                httpsAgent: new https.Agent({
                    rejectUnauthorized: false
                }),
                data: body,
                auth: {
                    username: user,

                    password: password,

                },
            }, );
```

ERROR :

stack:"TypeError: Cannot read property 'raxConfig' of undefined\n    
odeceptjs\node_modules\retry-axios\build\src\index.js:29:31)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"

**Comment by konstantinblaesi** [comment]
why are you not calling `rax.attach();`?

**Comment by troykelly** [comment]
This is fixed with https://github.com/JustinBeckwith/retry-axios/pull/70
But I can't create a PR because it says the commit message is empty - it is not.
