### ISSUE TITLE
Custom HttpsAgent gets corrupted after retry

### ISSUE THREAD

**Issue by denizaydemir** [JustinBeckwith/retry-axios#60]
Using a custom HttpsAgent to make requests over proxy. Whenever a request fails, rax tries to retry the request but following error occurs.

The "options.agent" property must be one of type Agent-like Object, undefined, or false. Received type object
TypeError [ERR_INVALID_ARG_TYPE]: The "options.agent" property must be one of type Agent-like Object, undefined, or false. Received type object
    at new ClientRequest (_http_client.js:112:11)
    at Object.request (https.js:303:10)
    at dispatchHttpRequest (/xxx/node_modules/axios/lib/adapters/http.js:141:25)
    at new Promise (<anonymous>)
    at httpAdapter (/xxx/node_modules/axios/lib/adapters/http.js:18:10)
    at dispatchRequest (/xxx/node_modules/axios/lib/core/dispatchRequest.js:59:10)

Before the "retry" trials, custom agent and all the requests works.

**Comment by denizaydemir** [comment]
Struggling with this issue for 2 days, finally came up with a solution. Instead of creating a custom agent in axios instance, I have modified the proxy object in axios/lib/adapters/http.js like following:
`if (proxy) {
          var proxyOpt = 'https://' + proxy.auth.username + ':' + proxy.auth.password + '@' + proxy.host + ':' + proxy.port
          options.agent = isHttps ? (new HttpsProxyAgent(proxyOpt)) : (new HttpProxyAgent(proxyOpt));
      }`

**Comment by JustinBeckwith** [comment]
Good to hear you were able to find a solution!
