### ISSUE TITLE
Retry method not working when using two axios requests

### ISSUE THREAD

**Issue by Kerdanyy** [JustinBeckwith/retry-axios#63]
When using two axios requests, the retry method works in the 1st request but doesn't work in 2nd request which is made after the 1st request. When calling the 2nd request an error is thrown and retry is not triggered.

Output: UnhandledPromiseRejectionWarning: Error: Request failed with status code 404 

Exmaple:

` rax.attach();
  
  **const res = await axios**({
       
 url: 'https://postman-echo.com',
       
 method: 'post',
   raxConfig: {
            // Retry 3 times on requests that return a response (500, etc) before giving up.  Defaults to 3.
            retry: 2,
            // Retry twice on errors that don't return a response (ENOTFOUND, ETIMEDOUT, etc).
            noResponseRetries: 2,
            // HTTP methods to automatically retry.  Defaults to:
            // ['GET', 'HEAD', 'OPTIONS', 'DELETE', 'PUT']
            httpMethodsToRetry: ['GET', 'POST', 'HEAD', 'OPTIONS', 'DELETE', 'PUT'],
            // The response status codes to retry.  Supports a double
            // array with a list of ranges.  Defaults to:
            // [[100, 199], [429, 429], [500, 599]]
            statusCodesToRetry: [[100, 199], [400, 499], [500, 599]],
            // Milliseconds to delay at first.  Defaults to 100.
            retryDelay: 100,
            onRetryAttempt: (err) => {
                const cfg = rax.getConfig(err);
                console.log(`Retry attempt #${cfg.currentRetryAttempt}`);
            }     }  }); `

` 
rax.attach();
**const res = await axios**({   
 url: 'https://postman-echo.com',
 method: 'post',

   raxConfig: {
            // Retry 3 times on requests that return a response (500, etc) before giving up.  Defaults to 3.
            retry: 2,
            // Retry twice on errors that don't return a response (ENOTFOUND, ETIMEDOUT, etc).
            noResponseRetries: 2,
            // HTTP methods to automatically retry.  Defaults to:
            // ['GET', 'HEAD', 'OPTIONS', 'DELETE', 'PUT']
            httpMethodsToRetry: ['GET', 'POST', 'HEAD', 'OPTIONS', 'DELETE', 'PUT'],
            // The response status codes to retry.  Supports a double
            // array with a list of ranges.  Defaults to:
            // [[100, 199], [429, 429], [500, 599]]
            statusCodesToRetry: [[100, 199], [400, 499], [500, 599]],
            // Milliseconds to delay at first.  Defaults to 100.
            retryDelay: 100,
            onRetryAttempt: (err) => {
                const cfg = rax.getConfig(err);
                console.log(`Retry attempt #${cfg.currentRetryAttempt}`);
            }   } });`

**Comment by DanielRuf** [comment]
How did you solve that?
