### ISSUE TITLE
Cannot set property 'raxConfig' of undefined

### ISSUE THREAD

**Issue by broom9** [JustinBeckwith/retry-axios#95]
The line below in the function `onError` sometimes throws error "Cannot set property 'raxConfig' of undefined"

It happened when an axios call encountered a 401 error.

```
// Put the config back into the err
    err.config.raxConfig = config;
```

Looks like the `err.config` could be `undefined`.

**Comment by JustinBeckwith** [comment]
Could you share what version of `retry-axios` you're running?  I think I fixed this bug :)

**Comment by broom9** [comment]
Sorry should have shared it in the first post.

I'm running retry-axios 2.1.1, axios 0.19.2. Both should be the latest versions.

**Comment by artur-ma** [comment]
It may happen when:
 1. You have another interceptor that throw  exception (in this case the error will not have config property)
2. One of your interceptors does not return the config object back

**Comment by broom9** [comment]
We have another error-handling response interceptor, which I think works after rax interceptor.

The error-handling response interceptor does `return Promise.reject(error);` on errors. It seems to be the standard way Axios doc suggests.

**Comment by artur-ma** [comment]
@broom9 this interceptor works on response, but u have an error on request, so if there is some code e.g

```
instance.interceptors.request.user((config) => {
  console.log(`this is my request #${num}`);
  return config;
});
```

Exception will be raised that variable `num` is not defined, but u will see another message in the logs,
"Cannot set property 'raxConfig' of undefined", since rax interceptor tries to access "config" object on the exception(that does not exist) 

Happened to me yesterday... luckily I found the real exception using debugger

**Comment by broom9** [comment]
@artur-ma thanks for the info. I searched through our codes but didn't find any request interceptor. We only added a response interceptor. It works basically like axios doc specifies:
```
axios.interceptors.response.use(function (response) {
    // Any status code that lie within the range of 2xx cause this function to trigger
    // Do something with response data
    return response;
  }, function (error) {
    // Any status codes that falls outside the range of 2xx cause this function to trigger
    // Do something with response error
    return Promise.reject(error);
  });
```
I think when 401 error happens, it goes into the response interceptor's error callback.

**Comment by artur-ma** [comment]
> I think when 401 error happens, it goes into the response interceptor's error callback.
Test it using: https://httpstat.us/401
